stages:
  - test

test:
  image: node:latest
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm install
    - npm i cypress --save-dev
    - npx cypress run